import Head from "next/head";
import Banner from "@/components/Banner/Banner";

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("Hi Banner Btn");
  };

  return (
    <>
      <Head>
        <title>Coffe Connoisseur </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner
          buttonTxt="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
      </main>
    </>
  );
}
